-----------------------------------------------------------
DROP TABLE FAQ;
DROP TABLE RATING;
DROP TABLE CARTITEM;
DROP TABLE CART;
DROP TABLE SHIPPING;
DROP TABLE PAYMENT;
DROP TABLE PROMOTION;
DROP TABLE PRODUCT;
DROP TABLE CUSTOMER;
-----------------------------------------------------------
CREATE TABLE CUSTOMER(
USERNAME VARCHAR(10) PRIMARY KEY,
C_PASSWORD VARCHAR(10) NOT NULL,
C_NAME VARCHAR(35) NOT NULL,
GROUPNAME VARCHAR(15) DEFAULT 'user' NOT NULL,
EMAIL VARCHAR(20)
);

INSERT INTO APP.CUSTOMER VALUES ('joe','joe','Joe','user','');
INSERT INTO APP.CUSTOMER VALUES ('ann','ann','Ann','user','ann@demo.com');
INSERT INTO APP.CUSTOMER VALUES ('admin','admin','Admin','admin','admin@demo.com');
-----------------------------------------------------------

CREATE TABLE PRODUCT(
ID INT PRIMARY KEY NOT NULL GENERATED ALWAYS AS IDENTITY(START WITH 1, INCREMENT BY 1),
P_NAME VARCHAR(35) NOT NULL,
PRICE DECIMAL(10,2) NOT NULL,
IMG_FILENAME VARCHAR(70),
MODEL_NAME VARCHAR(35) NOT NULL,
BRAND VARCHAR(35) NOT NULL
);

INSERT INTO APP.PRODUCT (P_NAME, PRICE, IMG_FILENAME, MODEL_NAME, BRAND) VALUES ('P1', 1000, 'Xperia-Z5.jpg', 'Xperia Z5', 'Sony');
INSERT INTO APP.PRODUCT (P_NAME, PRICE, IMG_FILENAME, MODEL_NAME, BRAND) VALUES ('P2', 2000, 'blackberry_priv.jpg', 'Priv','BlackBerry');
INSERT INTO APP.PRODUCT (P_NAME, PRICE, IMG_FILENAME, MODEL_NAME, BRAND) VALUES ('P3', 300, 'motorola-moto-g4.jpg', 'G4',  'Motorola Moto');
INSERT INTO APP.PRODUCT (P_NAME, PRICE, IMG_FILENAME, MODEL_NAME, BRAND) VALUES ('P4', 400, 'huawei-p9.jpg', 'P9', 'Huawei');
INSERT INTO APP.PRODUCT (P_NAME, PRICE, IMG_FILENAME, MODEL_NAME, BRAND) VALUES ('P5', 500, 'Nexus6P.jpg', '6P', 'Nexus');
INSERT INTO APP.PRODUCT (P_NAME, PRICE, IMG_FILENAME, MODEL_NAME, BRAND) VALUES ('P6', 600, 'iphone-6s.jpg', 'iPhone 6S', 'Apple');
INSERT INTO APP.PRODUCT (P_NAME, PRICE, IMG_FILENAME, MODEL_NAME, BRAND) VALUES ('P7', 700, 'oneplus-3.jpg', '3', 'OnePlus');
INSERT INTO APP.PRODUCT (P_NAME, PRICE, IMG_FILENAME, MODEL_NAME, BRAND) VALUES ('P8', 800, 'HTC-10.jpg', '10', 'HTC');
INSERT INTO APP.PRODUCT (P_NAME, PRICE, IMG_FILENAME, MODEL_NAME, BRAND) VALUES ('P9', 900, 'appleiphone7.jpg', 'iPhone 7 Plus', 'Apple');
INSERT INTO APP.PRODUCT (P_NAME, PRICE, IMG_FILENAME, MODEL_NAME, BRAND) VALUES ('P10', 1000, 'G7.jpg', 'Galaxy S7', 'Samsung');
INSERT INTO APP.PRODUCT (P_NAME, PRICE, IMG_FILENAME, MODEL_NAME, BRAND) VALUES ('P11', 1100, 'iph7.jpg', 'iPhone 7', 'Apple');
INSERT INTO APP.PRODUCT (P_NAME, PRICE, IMG_FILENAME, MODEL_NAME, BRAND) VALUES ('P12', 1200, 'goopixel.jpg', 'Pixel', 'Google');
INSERT INTO APP.PRODUCT (P_NAME, PRICE, IMG_FILENAME, MODEL_NAME, BRAND) VALUES ('P13', 1300, 's7edge.jpg', 'Galaxy S7 edge', 'Samsung');
INSERT INTO APP.PRODUCT (P_NAME, PRICE, IMG_FILENAME, MODEL_NAME, BRAND) VALUES ('P14', 1400, 'z3deluxe.jpg', 'ZenFone 3 Deluxe', 'Asus');
INSERT INTO APP.PRODUCT (P_NAME, PRICE, IMG_FILENAME, MODEL_NAME, BRAND) VALUES ('P15', 1500, 'nexus5x.jpg', '5X', 'Nexus');

-----------------------------------------------------------
CREATE TABLE PAYMENT(
ID INT PRIMARY KEY NOT NULL GENERATED ALWAYS AS IDENTITY(START WITH 1, INCREMENT BY 1),
P_METHOD VARCHAR(25) DEFAULT '',
ID_NUMBER VARCHAR(5) DEFAULT '',
CUSTOMER_ID VARCHAR(10) NOT NULL,
CONSTRAINT P_C_FK FOREIGN KEY(CUSTOMER_ID) REFERENCES CUSTOMER(USERNAME) ON DELETE CASCADE
);

CREATE TABLE SHIPPING(
ID INT PRIMARY KEY NOT NULL GENERATED ALWAYS AS IDENTITY(START WITH 1, INCREMENT BY 1),
ADDRESS VARCHAR(50) DEFAULT '',
CUSTOMER_ID VARCHAR(10) NOT NULL,
CONSTRAINT S_C_FK FOREIGN KEY(CUSTOMER_ID) REFERENCES CUSTOMER(USERNAME) ON DELETE CASCADE
);

CREATE TABLE CART(
ID INT PRIMARY KEY NOT NULL GENERATED ALWAYS AS IDENTITY(START WITH 1, INCREMENT BY 1),
CUSTOMER_ID VARCHAR(10) NOT NULL,
C_STATUS VARCHAR(15) DEFAULT 'unpaid',
DATE_PURCHASED DATE DEFAULT '',
SHIPPING_ID INT,
PAYMENT_ID INT,
CONSTRAINT C_S_FK FOREIGN KEY(SHIPPING_ID) REFERENCES SHIPPING(ID) ON DELETE CASCADE,
CONSTRAINT C_P_FK FOREIGN KEY(PAYMENT_ID) REFERENCES PAYMENT(ID) ON DELETE CASCADE,
CONSTRAINT C_C_FK FOREIGN KEY(CUSTOMER_ID) REFERENCES CUSTOMER(USERNAME) ON DELETE CASCADE
);

CREATE TABLE CARTITEM(
ID INT PRIMARY KEY NOT NULL GENERATED ALWAYS AS IDENTITY(START WITH 1, INCREMENT BY 1),
QUANTITY INT DEFAULT 0,
CART_ID INT,
PRODUCT_ID INT, 
CONSTRAINT CI_CT_FK FOREIGN KEY(CART_ID) REFERENCES CART(ID) ON DELETE CASCADE,
CONSTRAINT CI_P_FK FOREIGN KEY(PRODUCT_ID) REFERENCES PRODUCT(ID) ON DELETE CASCADE
);

CREATE TABLE PROMOTION(
PROMO_ID INT PRIMARY KEY NOT NULL GENERATED ALWAYS AS IDENTITY(START WITH 1, INCREMENT BY 1),
DISCOUNT_AMT INT,
PRODUCT_ID INT,
START_DATE DATE,
END_DATE DATE,
CONSTRAINT PM_PD_FK FOREIGN KEY(PRODUCT_ID) REFERENCES PRODUCT(ID) ON DELETE CASCADE
);


CREATE TABLE RATING(
ID INT PRIMARY KEY NOT NULL GENERATED ALWAYS AS IDENTITY(START WITH 1, INCREMENT BY 1),
PRODUCT_ID INT,
CUSTOMER_ID VARCHAR(10),
TITLE VARCHAR(25),
FEEDBACK VARCHAR(100),
PRODUCT_RATING INT,
CONSTRAINT R_P_FK FOREIGN KEY(PRODUCT_ID) REFERENCES PRODUCT(ID) ON DELETE CASCADE,
CONSTRAINT R_C_FK FOREIGN KEY(CUSTOMER_ID) REFERENCES CUSTOMER(USERNAME) ON DELETE CASCADE
);
-----------------------------------------------------------
CREATE TABLE FAQ(
ID INT PRIMARY KEY NOT NULL GENERATED ALWAYS AS IDENTITY(START WITH 1, INCREMENT BY 1),
QUESTION VARCHAR(100),
ANSWER VARCHAR(500),
FAQ_STATUS VARCHAR(25),
CUSTOMER_ID VARCHAR(10),
CONSTRAINT F_C_FK FOREIGN KEY(CUSTOMER_ID) REFERENCES CUSTOMER(USERNAME) ON DELETE CASCADE
);

INSERT INTO APP.FAQ (QUESTION, ANSWER, FAQ_STATUS, CUSTOMER_ID) VALUES ('What does Shopify do?', 'Shopify is a complete ecommerce solution that allows you to set up a user account and lets you purchase the latest smart phones available in our online store with credit card facility — all with a few clicks of the mouse.', 'Approved', 'admin');
INSERT INTO APP.FAQ (QUESTION, ANSWER, FAQ_STATUS, CUSTOMER_ID) VALUES ('How do I install Shopify?', 'Shopify is web based ecommerce software. This means there’s no installation required and it works with all operating systems (including Windows and MacOS)! We host Shopify so you don’t have to worry about installing, upgrading or maintaining any software or web servers.', 'Approved', 'admin');
INSERT INTO APP.FAQ (QUESTION, ANSWER, FAQ_STATUS, CUSTOMER_ID) VALUES ('What do I need in order to start buying the products?', 'All you need to know about buying products online from Shopify, is to sign up with an account and choose your desired product from our variety of latest smart phone collection and a credit card to pay for your purchase.', 'Approved', 'admin');
-----------------------------------------------------------
